tabe MainProcess/main.js
tabe Renderer/index.html
tabe Renderer/css/PhotoCollectionManager.css
tabe Renderer/css/PictureDisplay.css
tabe Renderer/about.html
tabe Renderer/js/PhotoCollectionManager.js
tabe Renderer/js/ImageDisplayManagement.js
tabe Renderer/js/ImageFaceHandling.js
tabe Renderer/js/DrawBox.js
tabe Renderer/js/FaceInfo.js
tabe Renderer/js/AlbumData.js
